### ISSUE TITLE
Travis CI에서 AWS S3/CDN 배포

### ISSUE THREAD

**Issue by OhMinsSup** [OhMinsSup/tip-review#4]
```yml
language: node_js
node_js:
  - "10.14" # node_js에 버전 10.14.1

# Git 커밋을 한 내용중 수신 허용 목록을
# 사용하여 분기를 포함하거나 차단 목록을 사용하여 분기를 제외하십시오.
branches:
  # safelist
  only:
    - master

# Travis CI는 자주 변경되지 않는 컨텐츠를 캐시하여 빌드 프로세스의 속도를 높일 수 있습니다.
# 캐싱 기능을 사용하려면 저장소 설정에서 Build Bushed Branch를 ON으로 설정하십시오.
cache:
  directories:
    - "node_modules"

script:
  - npm test

before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm run build

deploy:  # 배포
  provider: s3
  skip_cleanup: true #  Travis CI가 빌드 아티팩트를 삭제하지 못하도록하기위해
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에 설정된 값
  bucket: "veloss-creatix-deploy" # S3에 생성한 버킷
  region: ap-northeast-2
  local_dir: build # build 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
  acl: public_read
  on:
    repo: OhMinsSup/creatix-client #Github 주소
    branch: master

after_deploy:
  # 대상 배포판의 모든 객체를 무효화합니다.
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master'
# 빌드 성공및 실패에 대한 알림을 받을 이메일
notifications:
  email:
    recipients:
      - mins5190@gmail.com
```
